### DISCUSSION TITLE
Minimal service account permissions

### DISCUSSION THREAD

**Discussion by steache** [aptakube/aptakube#222] [Q&A] [answered]
Hello,

what is the minimal permission, that a service account has to have in order to be able to connect to the gui and view something? :)

Sorry for this noob question, while working with admin tokens etc., this does not make any sense, but we started to work with read-only service accounts with limited rbac (like only to list ingresses in all namespaces).

I can use this token to list the ingresses, but I'm not able to list the ingresses via aptakube. (get, list ,watch) here is an example of minimal token we are trying to use.

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: samuel-role
rules:
  - apiGroups: [ "" ]
    resources: [ "ingresses" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "networking.k8s.io" ]
    resources: [ "ingresses" ]
    verbs: [ "get", "list", "watch" ]
```

- service account with this cluster role attached, can list all ingresses and watch for changes, but in aptakube, we fail at "failed to load the cluster of context: minimal-rbac"
- the kubeconfig for this minimal-rbac has current-context defined, it's matching the one from available contexts, clusters are matching, users are matching :)
- PS, we have the same problem with lens, so it't 99% my fault

thank you for any help! :)

**Comment by goenning** [comment, marked as answer]
Hi @steache 

I think the issue you’re having is in your kubeconfig.

> failed to load the cluster of context: minimal-rbac

it seems like your context is referencing a cluster that could not be found in your config.

would you mind reviewing that or sharing your config (remove any sensitive information)

**Reply by steache** [reply]
Sorry @goenning, you are correct.
I still don't see the issue, I'm probably blind, but I've copied all settings except for the user.token from other kubeconfig and it works.

**Reply by steache** [reply]
@goenning sorry to bother you one more time, but I love how aptakube displays cpu/ram usage without any problems (for pod, node etc.), does it just call prometheus in my cluster, or? :) (I'm asking how to add this ability for our user tokens)

**Reply by steache** [reply]
found the answer, thank you :) 

```yaml
  - apiGroups: [ "metrics.k8s.io" ]
    resources: [ "pods", "nodes" ]
    verbs: [ "get", "list" ]
```
