### ISSUE TITLE
last log line is missing

### ISSUE THREAD

**Issue by mschneider82** [aptakube/aptakube#105]
### Current and expected behavior

When i show the logs of a Successfuly terminiated Job Pod, the last log line is missing
```
2023-05-11 09:31:12.208Z 2:00 {
2023-05-11 09:31:12.208Z 2:00   "status" : 200,
2023-05-11 09:31:12.208Z 2:00   "location" : "/rest/v1/test.zip"
Stream closed: EOF
```

In Lens there is a line with `}`  maybe missing \n here?

### Environment & Operating System

ubuntu latest appimage

**Comment by goenning** [comment]
Hey, thanks for the report.

I've been trying to reproduce this, but I can't...

I used this deployment for example:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: print
  labels:
    app: print
spec:
  replicas: 1
  selector:
    matchLabels:
      app: print
  template:
    metadata:
      labels:
        app: print
    spec:
      containers:
        - name: abc
          image: busybox:1.28
          args: [/bin/sh, -c, 'echo -e "{\n"status" : 200,\n"location" : "/rest/v1/test.zip"\n}"']
```

And the output looks ok.

![Screenshot 2023-05-11 at 15 14 00](https://github.com/aptakube/aptakube/assets/94755/3138fb65-99e8-4c3c-ab20-5238c49da890)

1. Can you just double check you're looking at the same pod?
2. Is it intermittent? If you switch to YAML tab and back to log multiple times, does it always print EOF before showing the last `}`?
