### ISSUE TITLE
Port forwarding not working when service port and service targetPort are not the same

### ISSUE THREAD

**Issue by pallxk** [aptakube/aptakube#175]
### Current and expected behavior

**Current behaviour:**

When a service specifies A as the port of the service (1234 in the example below), while targeting port B of matched pods (5678 in the example), the port forwarding of Aptakube will target port A of matched ports, leading to invalid port forwarding.

**Expected behaviour:**

When a service specifies A as the port of the service, while targeting port B of matched pods, the port forwarding of Aptakube should target port B of matched ports.

**Example spec:**

```yaml
spec:
  ports:
    - name: http
      protocol: TCP
      port: 1234            # A
      targetPort: 5678      # B
```

### Environment & Operating System

macOS Sonoma
Kubernetes v1.27.4+orb1
