### ISSUE TITLE
BadCertificate error on teleport session expiration

### ISSUE THREAD

**Issue by everpcpc** [aptakube/aptakube#179]
### Current and expected behavior

When using with teleport, refresh fails when session exipres. I have to quit and open aptakube again to trigger another authentication workflow.

### Environment & Operating System

macOS

**Comment by goenning** [comment]
I’m not very familiar with teleport, so I need to do a bit of reading on this.

Do they modify the server certificate when the session expires?

**Comment by everpcpc** [comment]
The configuration for a cluster with teleport is 
```
- name: example-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - kube
      - credentials
      - --kube-cluster=kubeClusterName
      - --teleport-cluster=teleportClusterName
      - --proxy=teleport.example.com:443
      command: /opt/homebrew/bin/tsh
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
```
