### ISSUE TITLE
multiple environment variables showing when using envFrom

### ISSUE THREAD

**Issue by jwhitcraft** [aptakube/aptakube#205]
### Current and expected behavior

I have this example yaml:

```
---
apiVersion: v1
kind: Secret
metadata:
  namespace: default
  name: test-secret
data:
  TEST: Q09ORklHTUFQX1ZBTFVF
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: test-config
data:
  TEST: "CONFIGMAP_VALUE"
---
apiVersion: v1
kind: Pod
metadata:
  name: busy
  namespace: default
spec:
  containers:
  - name: busybox
    image: busybox
    envFrom:
    - configMapRef:
        name: test-config
    - secretRef:
        name: test-secret
    env:
    - name: TEST
      value: "DEFAULT_VAULT"
    command:
    - "sh"
    - "-c"
    - >
      while true; do
        echo "$(TEST)";
        sleep 3600;
      done
```

When applied, inside of Aptakube, i see the following which is confusing:

<img width="358" alt="image" src="https://github.com/aptakube/aptakube/assets/26738/a5ed1aa9-b373-4e3c-aa9e-48790562de74">

As according to the [api spec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#container-v1-core) for **envFrom**

```
List of sources to populate environment variables in the container. The keys defined within a source must be a C_IDENTIFIER. All invalid keys will be reported as an event when the container is starting. When a key exists in multiple sources, the value associated with the last source will take precedence. Values defined by an Env with a duplicate key will take precedence. Cannot be updated.
```

I would believe that if a key is also present from the normal **Env** definition that aptakube shouldn't be showing the duplication keys if they come from **envFrom**

eg, my above example displaying in Aptakue would only show one Env Var, and it would be ```TEST: DEFAULT_VAULT```

### Environment & Operating System

MacOS 14.2.1, M2 Max, K8S 1.27 and 1.28
