### ISSUE TITLE
Service port forwarding bug

### ISSUE THREAD

**Issue by khalid244** [aptakube/aptakube#226]
### Current and expected behavior

I have a service pointing to two pods. When I try to forward the service, I find out it does not work, but when I do it using a lens it works great. So I did some debugging and I found out that the system was forwarding to the wrong port. The system will forward to 80 instead of 8000. Here is an example.

```
apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
....
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
      ports:
        - containerPort: 8000
          name: http
          protocol: TCP
....
```

### Environment & Operating System

macOS 14.1.1 (23B81)
