### ISSUE TITLE
Restart statefulsets without adding annotation

### ISSUE THREAD

**Issue by csdaraujo** [aptakube/aptakube#233]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

When using IaC, statefulset annotations are managed by code and should not be tweaked by Aptakube which happens when the restart feature is used. This approach can trigger two restarts: one by Aptakube (adding annotation) and another by the IaaC tool (removing annotation).

This is the annotation seen on `spec.template.metadata.annotations` when using Aptakube restart feature:
`"aptakube.com/restartedAt" = "2024-05-27T14:02:34.636126Z"`

So, instead of adding an annotation to the pod template, the proper API request(s) should be used (similar to `kubectl rollout`) and annotations kept untouched.

**Comment by goenning** [comment]
Hi @csdaraujo 

That's what kubectl rollout does too, here's an example of a restart with both kubectl and then later with Aptakube:

```yaml
  template:
    metadata:
      annotations:
        aptakube.com/restartedAt: 2024-05-27T14:39:23.421359Z
        kubectl.kubernetes.io/restartedAt: 2024-05-27T15:38:17+01:00
```

Is it possible that your IaaC tool ignores the `kubectl.kubernetes.io/restartedAt` annotation?
