### ISSUE TITLE
Env var using `valueFrom.fieldRef` are not showing in the container view

### ISSUE THREAD

**Issue by mboutet** [aptakube/aptakube#258]
### Current and expected behavior

It doesn't show:

<img width="320" alt="image" src="https://github.com/user-attachments/assets/53eb4ac1-e40e-4389-b145-faa347e28697">

Snippet from StatefulSet manifest:
```yaml
        - name: WORKER_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
```

### Environment & Operating System

```
macOS 13.6.2 (22G320)

On-prem ClusterAPI cluster
Server Version: version.Info{Major:"1", Minor:"28", GitVersion:"v1.28.5", GitCommit:"506050d61cf291218dfbd41ac93913945c9aa0da", GitTreeState:"clean", BuildDate:"2023-12-19T13:32:53Z", GoVersion:"go1.20.12", Compiler:"gc", Platform:"linux/amd64"}

Aptakube Version 1.6.10 (20240617.144003)
```
