### ISSUE TITLE
Support  client.authentication.k8s.io exec for kube config

### ISSUE THREAD

**Issue by grassdionera** [aptakube/aptakube#27]
### What problem are you trying to solve?

We are using exec command for client authentication in kube/config. currently aptakube returns

```Connection Error
auth error: failed to parse auth exec output: EOF while parsing a value at line 1 column 0
```

```yaml
- name: example-one
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1
      args:
      - lookup
      - account
      - example-one
      command: secret-tool
      env: null
      interactiveMode: Never
      provideClusterInfo: false
- name: example-two
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1
      command: k8s-secret.sh
      interactiveMode: Never
      provideClusterInfo: true
```

Below is the example output that the secret-tool returns

```json
{"apiVersion": "client.authentication.k8s.io/v1","kind": "ExecCredential","status": {"clientCertificateData": "-----BEGIN CERTIFICATE-----****MASKED****-----END CERTIFICATE-----","clientKeyData": "-----BEGIN PRIVATE KEY-----******MASKED*****-----END PRIVATE KEY-----"}}
``` 

### Describe the solution you'd like

working authentication with the exec command

**Comment by goenning** [comment]
hey @grassdionera 

Aptakube partially supports `exec`, but based on your error message, it seems like the command is not printing anything, not even an empty line, as it reached EOF on the first line, column 0.

If you try this:

```
  - name: docker-desktop
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1
        command: echo
        args:
          - '{}'
        env: null
        interactiveMode: Never
        provideClusterInfo: false
```

You should get this error `exec-plugin response did not contain a status` as the JSON is empty. Is there any condition in which secret-tool would not print anything to stdout?

---

I mentioned partially because Aptakube does not support `clientCertificateData` and `clientKeyData` yet, this is coming on the next version.
