### ISSUE TITLE
Add Phase to Pods list

### ISSUE THREAD

**Issue by TrueWill** [aptakube/aptakube#282]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

Would it be feasible to add the Phase field to the Pods grid? I frequently have to pull up pods that have Phase: Failed, but there's no obvious way to see these from the list. Status will be Completed.

Thank you!

**Comment by goenning** [comment]
They should show as "Error", like this:

<img width="639" alt="Screenshot 2024-08-30 at 12 47 58" src="https://github.com/user-attachments/assets/99b4b11f-94f0-40cf-b600-c05da023c35a">

If they're not, would you mind sharing the "status.containerStatuses" field of your pod?

Example YAML I used:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: exit-code-1-pod
spec:
  containers:
  - name: exit-container
    image: busybox
    command: ["/bin/sh", "-c", "exit 1"]
  restartPolicy: Never
```

**Comment by TrueWill** [comment]
Thank you - I didn't find any examples currently, but I'll watch for them and grab that section of the YAML the next time it comes up.

**Comment by TrueWill** [comment]
We addressed the root cause, so these issues are rare now. When they do come up the pods are deleted before I have a chance to examine them.

Here's an example from one that succeeded in case that helps:

```yaml
  containerStatuses:
    - name: main
      state:
        terminated:
          exitCode: 0
          reason: Completed
          startedAt: 2024-09-20T15:49:11Z
          finishedAt: 2024-09-20T15:54:25Z
          containerID: containerd://...
      lastState: {}
      ready: false
      restartCount: 0
      image: ...
      imageID: ...
      containerID: ...
      started: false
    - name: wait
      state:
        terminated:
          exitCode: 0
          reason: Completed
          startedAt: 2024-09-20T15:49:10Z
          finishedAt: 2024-09-20T15:54:26Z
          containerID: ...
      lastState: {}
      ready: false
      restartCount: 0
      image: ...
      imageID: ...
      containerID: ...
      started: false
```
