### ISSUE TITLE
default templates should match 

### ISSUE THREAD

**Issue by gk-fschubert** [aptakube/aptakube#332]
### Current and expected behavior

not a bug but a issue in my opinion. 

The default templates don't match each other. 

the template for "Create Resource" under `Deployments` does not match the template for "Create Resource" under `Services`. 

The app selector under `Services` does not match the app label set on the deployment: 

Deployment: 
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

Service
```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  selector:
    app.kubernetes.io/name: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
```

Either the label of the deployemnt should be changed to `app.kubernetes.io/name` or the service selector should be changed to `app`. 

Secondly the `targetPort` in the service also don't matches the port of the deployment. 

### Environment & Operating System

macOS sequoia
