### ISSUE TITLE
Do not auto use namespace inside kubeconfig

### ISSUE THREAD

**Issue by zzjin** [aptakube/aptakube#364]
### Current and expected behavior

IWE have one kubefile that connects to a cluster with one namespace access. But when using this kubeconfig to connect to, aptakube opens window with `default` namespace, witch we do not have rights to manage.
Ans also, since this kubeconfig file cannot list cluster's all namespaces, we cannot see any namepsace at top box and can only type the right namespace in it.

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: xxx=
    server: https://internal.com:6443
  name: zzjin
contexts:
- context:
    cluster: zzjin
    namespace: ns-w70pytki
    user: w70pytki
  name: w70pytki@zzjin
current-context: w70pytki@zzjin
kind: Config
preferences: {}
users:
- name: w70pytki
  user:
    token: xxx
```

![image](https://github.com/user-attachments/assets/371049ca-158f-4e75-9ddc-fe0f52a5f5ab)
  

### Environment & Operating System

Aptakube: 1.9.1
