### ISSUE TITLE
Opening a shell results in "error: context "\"my-cluster-name\"" does not exist"

### ISSUE THREAD

**Issue by nicholasriviera** [aptakube/aptakube#372]
### Current and expected behavior

Since version 1.10.0, when I open a shell via the "Open Shell" icon on a container, my terminal (Windows Terminal, running cmd.exe) opens and logs following error instead of connecting to the pod:

`error: context "\"my-cluster-name\"" does not exist`

This also occurs in 1.10.2. It does not occur in 1.9.1.

Could this be related to the fix for https://github.com/aptakube/aptakube/issues/367?

### Environment & Operating System

Windows 10
Kubernetes 1.30.5 on AKS

**Comment by goenning** [comment]
Would you mind sharing your kubeconfig file (masking any sensitive data)?

**Comment by nicholasriviera** [comment]
Sure:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0...
    server: https://my-cluster-name.privatelink.westeurope.azmk8s.io:443
  name: my-cluster-name
contexts:
- context:
    cluster: my-cluster-name
    namespace: idm
    user: clusterUser_my-resource-group-name_my-cluster-name
  name: my-cluster-name
current-context: my-cluster-name
kind: Config
preferences: {}
users:
- name: clusterUser_my-resource-group-name_my-cluster-name
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - "--environment"
      - AzurePublicCloud
      - "--server-id"
      - 6dae42f8-4368-4678-94ff-3960e28e3630
      - "--client-id"
      - 80faf920-1908-4b52-b5ef-a8e7bedfc67a
      - "--tenant-id"
      - ...
      - "--login"
      - devicecode
      command: kubelogin
      env: null
      installHint: |

        kubelogin is not installed which is required to connect to AAD enabled cluster.

        To learn more, please go to https://aka.ms/aks/kubelogin
      interactiveMode: IfAvailable
      provideClusterInfo: false
```

Task Manager shows following command being executing when opening a shell in 1.10.2:

`cmd  /k kubectl exec activemq-75f9c69b57-ft68p --context \"my-cluster-name\" -n idm --stdin --tty -c activemq -- sh -c "clear; /bin/echo -e '\033[1;4;32mmy-cluster-name\033[0m 👉 Connected to container \033[1;4;36mactivemq\033[0m on pod \033[1;4;36midm\033[0m / \033[1;4;36mactivemq-75f9c69b57-ft68p\033[0m\n'; (bash || ash || sh)`

... versus in 1.9.1:

`cmd  /k kubectl exec activemq-75f9c69b57-ft68p --context my-cluster-name -n idm --stdin --tty -c activemq -- sh -c "clear; /bin/echo -e '\033[1;4;32mmy-cluster-name\033[0m 👉 Connected to container \033[1;4;36mactivemq\033[0m on pod \033[1;4;36midm\033[0m / \033[1;4;36mactivemq-75f9c69b57-ft68p\033[0m\n'; (bash || ash || sh)`
