### ISSUE TITLE
too many open files on Mac OS

### ISSUE THREAD

**Issue by RonStein2000** [aptakube/aptakube#408]
### Current and expected behavior

In my Mac based Aptakub I very often see this in the logs

init-config Stream closed: failed to create fsnotify watcher: too many open files
init-config Stream closed: EOF

and cannot view the log continuously but have to switch back and forth to have it refreshed.
I have set the open file limits on my MacOS to maximum, but this seems not to have helped. Is there any configuration or trick I can use, to increase the limit for Aptakube?

### Environment & Operating System

Mac OS 15.3.1

**Comment by goenning** [comment]
I've never had this issue before, and I think I haven't even changed the open file limits on my mac.

Have you noticed any pattern on when that happens?

Is it when looking at pod logs? the Overview tab?
When you select a lot of contexts?

**Comment by RonStein2000** [comment]
Hi, thanks for following up on this. It happens mainly, when I have more than one window open in Aptakube with the same of different contexts. But I have l also seen it with just 1 window open. Can I gather more information for you by doing something in Aptakube?

**Comment by goenning** [comment]
I'm honestly not sure how to troubleshoot this.I'm not seeing anything that could indicate a leak of open files. Do you usually have a lot of other things running at the time that may be opening more files than usual?

**Comment by jonathanrdelgado** [comment]
hey, I was just having the exact same thing. I initially was thinking I had a ulimit problem locally too, but quickly realized it was my k3s server itself.

@RonStein2000 Lookup whatever commands for your own distro/version of Kubernetes server, but for Ubuntu 24, I edited `/etc/security/limits.conf` and added
```
* soft nofile 65536
* hard nofile 65536
```

Bonus, if you use Ansible:
```yaml
- name: Ensure soft/hard nofile limits
  community.general.pam_limits:
    domain: '*'
    limit_type: '{{ item.limit_type }}'
    limit_item: nofile
    value: 65536
  loop:
    - { limit_type: 'soft' }
    - { limit_type: 'hard' }
```

After a server restart, the error was resolved!
