### ISSUE TITLE
Unable to view init container logs in deployments page

### ISSUE THREAD

**Issue by thorweijie** [aptakube/aptakube#456]
### Current and expected behavior

Current behaviour: When I was investigating the native sidecar resource issue (#452), I noticed that in pods page (second image), I can see the logs of the nginx main container, as well as the 2 init containers (istio-validation and istio-proxy). However in deployments page (third image), I can only see the logs of the nginx main container.

Expected behaviour: I expect to see 3 containers (1 pod x (1 main container + 2 init containers)) in deployments page.

<img width="854" alt="Image" src="https://github.com/user-attachments/assets/acc01400-e0d9-4039-9c73-9350a4c2b98d" />
<img width="1553" alt="Image" src="https://github.com/user-attachments/assets/a10b4e9f-3283-4d10-9293-ed6acd7b94e9" />
<img width="1538" alt="Image" src="https://github.com/user-attachments/assets/31ac9354-756e-491b-9ad0-6b70872513b4" />

### Environment & Operating System

macOS Sequoia 15.5

**Comment by goenning** [comment]
Hey @thorweijie I've been working on a new version of the log viewer (with a bunch of other features/improvements), and this bug should be fixed on it. Would you like to give it a try?

https://releases.aptakube.com/Aptakube_1.12.0-beta4_universal.dmg

**Comment by thorweijie** [comment]
@goenning I am still unable to view init container logs in deployments view. On an unrelated note, is it possible to add sidecar containers to the pods view so it's easier to exec into the container? In the first image, I would like to see istio-proxy present, in addition to nginx and nginx2.

<img width="857" height="879" alt="Image" src="https://github.com/user-attachments/assets/eedefea6-9175-4974-bbe8-0e0095f0dd06" />
<img width="1554" height="198" alt="Image" src="https://github.com/user-attachments/assets/aaff9bc4-40a7-4d57-8604-ee121383b89d" />

**Comment by goenning** [comment]
On your second image, there's nothing below the "Init Containers" label? The image seems cropped 

On your first image, the sidecar is there, below ngnix2. And there are buttons to exec into it. Did I miss something?

**Comment by thorweijie** [comment]
I've added a full screenshot, there's nothing below the init containers label
<img width="1556" height="983" alt="Image" src="https://github.com/user-attachments/assets/3fda17f6-803b-4db8-bc71-1d0044f86a31" />

I was wondering if it's possible to add a tab for istio-proxy at the top? So it's easier to jump to the container
<img width="1249" height="444" alt="Image" src="https://github.com/user-attachments/assets/cca4b687-4e78-416a-a270-eb57f7c64c2c" />

**Comment by goenning** [comment]
Would you mind sharing your nginx deployment YAML (remove anything sensitive). This is how it should look:

<img width="1274" height="474" alt="Image" src="https://github.com/user-attachments/assets/235ba7fa-fc84-406a-8799-dc00c9a27605" />

As for the tab, I think that makes sense 👍

**Comment by thorweijie** [comment]
Here is the deployment yaml, the init containers were injected by Istio's mutating webhook
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    sidecar.istio.io/inject: "true"
  name: nginx
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - image: nginx
          imagePullPolicy: Always
          name: nginx
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - image: nginx
          imagePullPolicy: Always
          name: nginx2
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```
