### ISSUE TITLE
Ingress TLS -> Still show http:// url

### ISSUE THREAD

**Issue by FilipK-CZ** [aptakube/aptakube#64]
### Current and expected behavior

I'm still getting http url even though ingress has defined in spec tls

Example:
```
spec:
  ingressClassName: traefik-internal
  tls:
    - hosts:
        - kube1.example.com
      secretName: kube1-example-com-tls
```

Result:
```
Path | URL → Backend
-- | --
/ (Prefix) | http://argo-cd.kube1.example.com/→argo-cd-argocd-server:80
```

Lens result:
```
Path | Link
-- | --
/ | https://argo-cd.kube1.example.com/
```

### Environment & Operating System

macOS Ventura 13.2
Kubernetes 1.26
