### ISSUE TITLE
Loading forever (timeout)

### ISSUE THREAD

**Issue by dmeijboom** [aptakube/aptakube#70]
### Current and expected behavior

For some reason I'm not able to connect to a cluster (with an internal IP address and valid certificate) anymore:

<img width="664" alt="Scherm­afbeelding 2023-02-16 om 20 56 36" src="https://user-images.githubusercontent.com/3341876/219473330-f496ce64-ac1a-44b7-96f5-4a6a2e5e271e.png">

Logs show nothing relevant (cleared them before retrying). Note that `kubectl get nodes` works just fine.

### Environment & Operating System

macOS 13.2
Kubernetes 1.25.5

**Comment by goenning** [comment]
Could you try using the previous version from here https://github.com/aptakube/aptakube/releases/tag/1.2.0

there’s been a few changes on 1.2.1 and I’m just wondering if this is a regression

Also, what you mean by “internal ip”? Is it a local cluster running in your laptop?

**Comment by dmeijboom** [comment]
Oops, seems like an issue on my end (duplicate context name). However, now it gives the following error:

> HyperError: error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:: unable to get local issuer certificate

**Comment by dmeijboom** [comment]
> Could you try using the previous version from here https://github.com/aptakube/aptakube/releases/tag/1.2.0

It doesn't work unfortunately (same error).

> there’s been a few changes on 1.2.1 and I’m just wondering if this is a regression

> Also, what you mean by “internal ip”? Is it a local cluster running in your laptop?

Its a cluster on the same network, imagine a Kubernetes API server running on something like `https://192.168.1.21:6443`.

**Comment by goenning** [comment]
Does your kubeconfig have multiple "clusters" with the same name? Maybe across different kubeconfig?

Otherwise we can chat on discord tomorrow to get this one sorted

**Comment by dmeijboom** [comment]
> Does your kubeconfig have multiple "clusters" with the same name? Maybe across different kubeconfig?

It did (one for local access and another for public access to the same cluster). But I renamed one of them so that is no longer an issue.

> Otherwise we can chat on discord tomorrow to get this one sorted

Yeah that would be great. Just to reiterate I get the following error now that the duplicate cluster name issue is resolved:

```log
HyperError: error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:: unable to get local issuer certificate
 ```

**Comment by dmeijboom** [comment]
> hey @dmeijboom in case you still have this cluster, would you like to try using this beta release?
> 
> I've had a few other cases in which openssl wasn't working, so I moved to rustls and it fixed a lot of the previous incompatibilities, as well as improving connection speed and reducing memory footprint.
> 
> 🍎 ➡️ https://releases.aptakube.com/Aptakube_1.3.3_universal.dmg 🪟 ➡️ https://releases.aptakube.com/Aptakube_1.3.3_x64_en-US.msi 🐧 ➡️ https://releases.aptakube.com/aptakube_1.3.3_amd64.deb / https://releases.aptakube.com/aptakube_1.3.3_amd64.AppImage

I tried it but got the following error: 
<img width="1624" alt="Scherm­afbeelding 2023-04-11 om 21 47 16" src="https://user-images.githubusercontent.com/3341876/231272614-fa4b57ec-99f6-424b-82cb-55a0fc495093.png">

Certificate used:

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 2165451423623571448 (0x1e0d3a98c37267f8)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=kubernetes
        Validity
            Not Before: Aug 21 09:03:25 2022 GMT
            Not After : Feb 16 19:35:36 2024 GMT
        Subject: CN=kube-apiserver
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    00:c8:d2:d8:7f:ac:97:03:3b:d7:24:26:bf:3e:6d:
                    8d:db:83:4f:6d:17:1b:c6:38:68:b9:16:dd:b9:6f:
                    ff:36:37:b5:2e:2e:55:37:33:a7:b6:ea:a9:47:bc:
                    e3:f9:df:04:d3:67:74:80:c9:bd:89:3d:26:11:27:
                    d7:56:63:05:c3:01:10:ea:6e:9e:33:ff:78:ab:e2:
                    64:1d:eb:7c:38:ed:a8:fe:7f:e9:db:cd:09:5f:7a:
                    32:56:fd:d5:12:06:67:1e:bf:c3:53:1e:da:45:fb:
                    80:55:46:56:87:93:2a:f7:5f:38:59:3e:8e:da:6e:
                    78:41:81:77:e3:32:48:6b:1c:f0:2d:2b:e0:3e:49:
                    80:c0:9d:ad:36:99:e4:17:9f:46:02:d4:3e:87:cc:
                    c7:51:24:04:a5:48:96:85:cf:b2:a0:07:83:74:d5:
                    6a:85:1a:e6:a0:98:01:a1:9a:57:a6:f8:bc:bb:1c:
                    1f:7c:67:1f:38:14:b2:2d:29:7e:2a:b8:63:86:14:
                    65:73:15:17:64:ca:21:58:8c:eb:a7:f8:65:2b:7a:
                    66:01:58:93:c2:cf:d2:45:4d:cb:2f:87:b5:f5:87:
                    d9:5c:91:7b:04:e4:82:a3:aa:80:73:66:e5:6b:8d:
                    14:07:21:2f:44:a4:8a:a5:d8:ae:31:54:82:86:f9:
                    90:cb
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage:
                TLS Web Server Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Authority Key Identifier:
                keyid:19:A6:1B:F7:1A:88:0B:E5:C8:EB:83:12:95:00:A5:E5:FA:98:26:14

            X509v3 Subject Alternative Name:
                DNS:control-plane.[redacted] DNS:[redacted], DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local, IP Address:10.96.0.1, IP Address:192.168.1.93, IP Address:192.168.1.21
    Signature Algorithm: sha256WithRSAEncryption
         0d:9f:d2:0e:c3:f7:5b:96:1a:e3:ab:3a:12:05:88:4a:c7:51:
         26:83:b2:ab:a1:a8:c2:b8:21:6e:7a:86:e2:c8:2c:1d:00:e9:
         fa:69:d7:30:25:3a:69:32:a9:8a:b5:b1:c2:3f:12:16:b7:c9:
         88:98:e8:20:36:cc:a0:ae:bb:60:a3:90:d9:8e:85:38:db:39:
         86:8e:58:20:51:c7:6d:8d:5a:e4:9e:c4:e6:55:67:ab:2b:54:
         d0:88:7c:a2:0e:fb:3e:5e:fc:28:7a:40:3b:ba:3f:0f:fd:9e:
         a6:78:15:d5:2d:24:97:5b:d6:b0:34:d7:a7:87:63:b8:60:ae:
         06:e0:56:de:86:63:47:78:18:69:de:be:22:be:a2:86:8b:99:
         47:17:58:02:52:8d:9b:64:ce:ab:06:22:a9:10:9e:86:3b:78:
         ef:2b:d2:7e:50:97:66:43:c6:5a:be:9c:ed:17:f0:71:ae:24:
         45:50:90:4c:09:da:f1:50:b1:cf:c5:34:36:da:27:ed:e9:ca:
         32:05:fc:71:f7:2f:06:ea:dc:9e:5b:3a:49:bc:0e:ff:62:98:
         0f:04:0b:c4:4b:37:4c:f4:49:74:88:8e:38:d5:a5:2c:46:a1:
         e3:df:5b:35:79:90:13:b9:33:77:f9:47:cc:ec:28:01:22:77:
         32:84:46:30
```

Note that both setting `certificate-authority-data` and `insecure-skip-tls-verify` don't work. It does feel like it's getting closer to it actually working though.

**Comment by goenning** [comment]
That's odd, even the `insecure-skip-tls-verify` didn't work? As far as I remember, it used to work with the previous Aptakube version, no? Do you mind sharing your `certificate-authority-data` either here or on Discord?

Unfortunately that `UnknownIssuer` message doesn't help much https://github.com/briansmith/webpki/issues/221 :(

**Comment by goenning** [comment]
One thing I noticed today is that rustls has some more meaningful logs than openssl had, can you also share the logs from `~/Library/Logs/com.aptakube.Aptakube/Aptakube.log` ?

**Comment by dmeijboom** [comment]
I shared the CA-data on discord and here are the relevant lines from the log:

```
[2023-04-11][19:53:38][rustls::common_state][WARN] Sending fatal alert UnknownCA
[2023-04-11][19:53:38][rustls::common_state][WARN] Sending fatal alert UnknownCA
[2023-04-11][19:53:38][rustls::common_state][WARN] Sending fatal alert UnknownCA
```

**Comment by carlmontanari** [comment]
👋 just wanted to chime in to say that I hit the same `UnknownCA` error after adding a self signed cert to root trust in keychain (macos) for the ingress sitting in front of a cluster (using loft + vlcusters). Sadly (for this thread, not for me) adding insecure skip verify to kubeconfig did solve this. FWIW/if it matters kubectl worked just fine w/out this but I got the same hyper error and unknown ca in log entries.

**Comment by goenning** [comment]
hey @carlmontanari thanks for your inputs

1. Have you set the CA data on your kubeconfig too or just added the cert to keychain?
2. It is easy to replicate this? I would like to get to the bottom of it but I need to replicate this first. Or, if this is a public throw away cluster that I could get access to, that'd work too!

**Comment by carlmontanari** [comment]
1. just quickly tested and seems like no (same cert in keychain exported as pem + b64 encoded and stuffed into `certificate-authority-data` in kubeconfig) got same error.
2. easy-ish yes :) -- if you have a cluster you can install loft into (basically download loft binary + `loft start` then create a vcluster (you can just click around to make that happen pretty easily) -- once thats done you can use loft to connect to the vcluster and that will run things through the loft proxy. up to that point things should "just work" -- then you'd have to set default cert in ingress controller like I did. im sure there's another way, just thats the way I know I can reproduce it. will try to poke about a bit more and report any findings when I get some time!

**Comment by goenning** [comment]
Thanks @carlmontanari I am not sure I followed all the steps correctly, because the end result was different.

1. I created a vcluster, downloaded the kubeconfig and it worked on both kubectl and aptakube because of the `insecure-skip-tls-verify: true` that comes by default. The server was `https://localhost:9898/kubernetes/project/default/virtualcluster/my-vcluster`

2. I installed nginx ingress controller and generated the ssl following these steps ( https://loft.sh/docs/getting-started/domain ).
 
But when I tried to set `DNS.1` to `localhost` like the docs suggested, I got an error on ingress controller saying the certificate was not valid because of missing alt names `loft.sligo.dev`, so I changed that to `DNS.1 = loft.sligo.dev` and it worked, nginx accepted the certificate.

The ssl config I used:
```
[ req ]
default_bits       = 4096
distinguished_name = req_distinguished_name
x509_extensions    = v3_ca
req_extensions     = v3_req
x509_extensions    = usr_cert

[ req_distinguished_name ]
organizationName          = Aptakube
organizationName_default  = loft
commonName                = Aptakube
commonName_default        = loft.sligo.dev

[ usr_cert ]
basicConstraints  = CA:FALSE
nsCertType        = client, server
keyUsage          = digitalSignature
extendedKeyUsage  = serverAuth, clientAuth

[ v3_req ]
subjectAltName   = @alt_names
extendedKeyUsage = serverAuth, clientAuth
basicConstraints = CA:FALSE
keyUsage         = digitalSignature

[ alt_names ]
DNS.1 = loft.sligo.dev
```

3. Then I changed the kubeconfig to:

```
apiVersion: v1
kind: Config
clusters:
- cluster:
    #server: https://localhost:9898/kubernetes/project/default/virtualcluster/my-vcluster
    #insecure-skip-tls-verify: true
    server: https://loft.sligo.dev/kubernetes/project/default/virtualcluster/my-vcluster
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZKekNDQXcrZ0F3SUJBZ0lKQU5TQlFrWnJkZ1hJTUEwR0NTcUdTSWIzRFFFQkN3VUFNQ2d4RFRBTEJnTlYKQkFvTUJHeHZablF4RnpBVkJnTlZCQU1NRG14dlpuUXVjMnhwWjI4dVpHVjJNQjRYRFRJek1EVXpNVEV3TXpFeApOVm9YRFRNek1EVXlPREV3TXpFeE5Wb3dLREVOTUFzR0ExVUVDZ3dFYkc5bWRERVhNQlVHQTFVRUF3d09iRzltCmRDNXpiR2xuYnk1a1pYWXdnZ0lpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElDRHdBd2dnSUtBb0lDQVFDNkRSTGIKVE5kU0JZei9LL1R3RVFhSEtheXhIeUd2azNZdStkQUw3bFh4THhnT2Q1UE9VSGJJdmFsQ1ZLQVcxYlE2V2xGRApwejhmUjUwcEJlam1BMXFMK0YwckkyOXpYaGlndWNpNTR5SmNLaWpYQXR1V3RRT0sxSFNNTHpGOHlhSTk3RzhGCjVNQ2loTEV2UG9rTWY3YTg1dkNrWFNBbUFOYjBTK3k2RmVSQ0sxMTV2Tmo0Y1JVQmZScUtZNmUvdDFoNytUTlUKRldBM0lDZ3Jld0FXRThTWGVmTnBmWWJ1eTRNZjZOTW1PeFIxNWxmRGdRK0FRVllPcEY5TGNJdFZQemR6KzJwLwpRSWR2SWhRa3FZVWdZZVE2VXFBZ0V1TjRoNlVqUC9xY1l3dWRUY3VHbVVXNGMvNExHZkhrVC9DYXFEbDRacjdKCnFXeVJQNWk4Y1YrTkhUOGQwQzdITnUzUThIb3owSVgzU1NRcGczbjIzVDJGeUlDMG5yYWJHcFJYVlRyemxnZ0IKejNjR3JBYWluUG5NNHRwL2ZVUlU2WU5peWxJWVdvWjFoR01SQXk0bGxONTVQNVZMbWRpMmRiL1pTTUpIMlFOMwpUVmx4Z1Y3bGNvU1U1NkplMytxNGpiekJRTnpsaWM5YlV6eWJhazB2bjh3YVNRYmN2ZnVGbWFCSkpLVWdHcEd4CmZzVjYxdExGSGtiLzF6KzhaMTVYbllRM0VMTVlES3pha3NyZXRJZEUxbk1Ed2VUNWtmYTVEbXFMeFhFZ3RuLzgKQjh2dGZrSUd3cDcrSjFyTmRwbmJDT25jTTZIZ0ZoM2cwWXZhRTc5R1ZldXVmZGx1Z0VJTXRuYzhFV2w4S2llawpyb2orMVh5RW5lRmhLYTM0WkRmVjF0QmpsRjFlSkVCaGQ3TEgxUUlEQVFBQm8xUXdVakFaQmdOVkhSRUVFakFRCmdnNXNiMlowTG5Oc2FXZHZMbVJsZGpBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXcKQ1FZRFZSMFRCQUl3QURBTEJnTlZIUThFQkFNQ0I0QXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnSUJBSU9Xd0ticApyaDJCYURrVThMZ20yNG1CSmFzempnaGZwdjlRZzQ2WjhHZUlCdmFNQkN5NTNpd2NQY1J0QU03SUhNTHFaWEUvCkd4bnNvWExkRXY4K3h4ekN1bzIzcWR3UFdocHZzczM4T0xqaWhlTFJZaHprcFd0enZDQ2ZCTEFIV01XWWcvRVkKYjh3bFRuaElieXNCL3IrTWV2clEzM1hjQ2JYVnNtbTBSZHhHeUVFOXJIT2pXZXc0L1ZxS0hqUW51bC9kUXN0UgovSnBDREF1Q1pOeXFBN3E3ZjV6RVJEaENGN3J1NmlRTWFxSHJiY1NSS1g3UEhnVnVIaXNsb2tpQytaUEpMWldHCjVVY1JkOUh2YUxXemp3cWtsSEhuekhPc1U1MWIvRU9mOEhPYkRrT2lGK25uakNSM3RCQ0hRbkhsOHhpQ2dBVHIKWDN1b3EvenpGM01xbHlVakFCcjBkaUtIOGNzMDY0OGQ4NFoyak9DbVZCRjVZUnJZem1ZaDNHWkdEVkZtUFR6WQpzdllxd3BXakpJNm5kdlN1azBLUG9vSXNlOVViUG1pL0phdGVWby9IcXhMd2NKTGl6eGdCZGloVmtHUS9FK2hqClRncFR2Y2NqeGVJSE5hNVc4TEgxU2M4MUp2cTZ0L3pkdmxWMndrYXcyS2NoYlRxeGVJUENmNDlzTnF4ZFJpSjAKdzFXbndMWTBvV1orMDBGUVp2V1BvcUxEaVQ2Q1JkZjFFeGNRUlVsSVFhcnkvVk9jSktTdE54SGhOVGluTmVHQQptQ3hGR2pUYnhyVmZxUzR3dUlTaUduTDFqRytIbzRQamRuZkhNTSszUHBjaC9oSWZWSHhQNllxa1dKTUNSdnFnCkxQb0wrRVdmWVNtU0ZYY3k1ZXRTdmN6VEdETTZzeTAvakoycAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  name: loft
contexts:
- context:
    cluster: loft
    user: loft
    
  name: loft
current-context: loft
users:
- name: loft
  user:
    token: bla
```

Which worked on both kubectl and aptakube. Can you try the config above? You should get a 401, but not a ssl error.
