### ISSUE TITLE
Properly parse additionalPrinterColumns in CRDs

### ISSUE THREAD

**Issue by fernandocarletti** [aptakube/aptakube#94]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

When the `additionalPrinterColumns` is set in a CRD as a string and the field is an array there is a difference between how the kubectl and Aptakube formats it:

1. kubectcl makes a json representation of the field. E.g. `["foo","bar","zaz"]`
2. Aptakube just concatenates everything: E.g. `foobarzaz`.

It would be great if it mimics the behavior of kubectl or, even better, make join the values with a comma.

**Comment by goenning** [comment]
Do you have an example of CRD with a string array column?

**Comment by fernandocarletti** [comment]
Here are the samples:

CRD:
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: groups.foo.com
spec:
  group: foo.com
  names:
    kind: Group
    listKind: GroupList
    plural: groups
    singular: group
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.members
      name: Members
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            required:
              - members
            properties:
              members:
                description: Members of the group
                type: array
                items:
                  type: string
    served: true
    storage: true
    subresources:
      status: {}
```

A sample:

```yaml
apiVersion: foo.com/v1alpha1
kind: Group
metadata:
  name: group-sample
spec:
  members:
    - ted.mosby
    - marshall.eriksen
    - lily.aldrin
```
